/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VipRouteImport } from './routes/vip'
import { Route as ServeryRouteImport } from './routes/servery'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as AdminTymRouteImport } from './routes/admin-tym'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NovinkyIndexRouteImport } from './routes/novinky.index'
import { Route as ForumIndexRouteImport } from './routes/forum.index'
import { Route as ServerIdRouteImport } from './routes/server.$id'
import { Route as NovinkyIdRouteImport } from './routes/novinky.$id'
import { Route as ForumSlugRouteImport } from './routes/forum.$slug'
import { Route as ForumSlugIndexRouteImport } from './routes/forum.$slug.index'
import { Route as ForumSlugTopicIdRouteImport } from './routes/forum.$slug.$topicId'

const VipRoute = VipRouteImport.update({
  id: '/vip',
  path: '/vip',
  getParentRoute: () => rootRouteImport,
} as any)
const ServeryRoute = ServeryRouteImport.update({
  id: '/servery',
  path: '/servery',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTymRoute = AdminTymRouteImport.update({
  id: '/admin-tym',
  path: '/admin-tym',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NovinkyIndexRoute = NovinkyIndexRouteImport.update({
  id: '/novinky/',
  path: '/novinky/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumIndexRoute = ForumIndexRouteImport.update({
  id: '/forum/',
  path: '/forum/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerIdRoute = ServerIdRouteImport.update({
  id: '/server/$id',
  path: '/server/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NovinkyIdRoute = NovinkyIdRouteImport.update({
  id: '/novinky/$id',
  path: '/novinky/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumSlugRoute = ForumSlugRouteImport.update({
  id: '/forum/$slug',
  path: '/forum/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumSlugIndexRoute = ForumSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ForumSlugRoute,
} as any)
const ForumSlugTopicIdRoute = ForumSlugTopicIdRouteImport.update({
  id: '/$topicId',
  path: '/$topicId',
  getParentRoute: () => ForumSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-tym': typeof AdminTymRoute
  '/kontakt': typeof KontaktRoute
  '/reset-password': typeof ResetPasswordRoute
  '/servery': typeof ServeryRoute
  '/vip': typeof VipRoute
  '/forum/$slug': typeof ForumSlugRouteWithChildren
  '/novinky/$id': typeof NovinkyIdRoute
  '/server/$id': typeof ServerIdRoute
  '/forum/': typeof ForumIndexRoute
  '/novinky/': typeof NovinkyIndexRoute
  '/forum/$slug/$topicId': typeof ForumSlugTopicIdRoute
  '/forum/$slug/': typeof ForumSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-tym': typeof AdminTymRoute
  '/kontakt': typeof KontaktRoute
  '/reset-password': typeof ResetPasswordRoute
  '/servery': typeof ServeryRoute
  '/vip': typeof VipRoute
  '/novinky/$id': typeof NovinkyIdRoute
  '/server/$id': typeof ServerIdRoute
  '/forum': typeof ForumIndexRoute
  '/novinky': typeof NovinkyIndexRoute
  '/forum/$slug/$topicId': typeof ForumSlugTopicIdRoute
  '/forum/$slug': typeof ForumSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-tym': typeof AdminTymRoute
  '/kontakt': typeof KontaktRoute
  '/reset-password': typeof ResetPasswordRoute
  '/servery': typeof ServeryRoute
  '/vip': typeof VipRoute
  '/forum/$slug': typeof ForumSlugRouteWithChildren
  '/novinky/$id': typeof NovinkyIdRoute
  '/server/$id': typeof ServerIdRoute
  '/forum/': typeof ForumIndexRoute
  '/novinky/': typeof NovinkyIndexRoute
  '/forum/$slug/$topicId': typeof ForumSlugTopicIdRoute
  '/forum/$slug/': typeof ForumSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-tym'
    | '/kontakt'
    | '/reset-password'
    | '/servery'
    | '/vip'
    | '/forum/$slug'
    | '/novinky/$id'
    | '/server/$id'
    | '/forum/'
    | '/novinky/'
    | '/forum/$slug/$topicId'
    | '/forum/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-tym'
    | '/kontakt'
    | '/reset-password'
    | '/servery'
    | '/vip'
    | '/novinky/$id'
    | '/server/$id'
    | '/forum'
    | '/novinky'
    | '/forum/$slug/$topicId'
    | '/forum/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-tym'
    | '/kontakt'
    | '/reset-password'
    | '/servery'
    | '/vip'
    | '/forum/$slug'
    | '/novinky/$id'
    | '/server/$id'
    | '/forum/'
    | '/novinky/'
    | '/forum/$slug/$topicId'
    | '/forum/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminTymRoute: typeof AdminTymRoute
  KontaktRoute: typeof KontaktRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServeryRoute: typeof ServeryRoute
  VipRoute: typeof VipRoute
  ForumSlugRoute: typeof ForumSlugRouteWithChildren
  NovinkyIdRoute: typeof NovinkyIdRoute
  ServerIdRoute: typeof ServerIdRoute
  ForumIndexRoute: typeof ForumIndexRoute
  NovinkyIndexRoute: typeof NovinkyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vip': {
      id: '/vip'
      path: '/vip'
      fullPath: '/vip'
      preLoaderRoute: typeof VipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servery': {
      id: '/servery'
      path: '/servery'
      fullPath: '/servery'
      preLoaderRoute: typeof ServeryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-tym': {
      id: '/admin-tym'
      path: '/admin-tym'
      fullPath: '/admin-tym'
      preLoaderRoute: typeof AdminTymRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novinky/': {
      id: '/novinky/'
      path: '/novinky'
      fullPath: '/novinky/'
      preLoaderRoute: typeof NovinkyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/': {
      id: '/forum/'
      path: '/forum'
      fullPath: '/forum/'
      preLoaderRoute: typeof ForumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server/$id': {
      id: '/server/$id'
      path: '/server/$id'
      fullPath: '/server/$id'
      preLoaderRoute: typeof ServerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novinky/$id': {
      id: '/novinky/$id'
      path: '/novinky/$id'
      fullPath: '/novinky/$id'
      preLoaderRoute: typeof NovinkyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/$slug': {
      id: '/forum/$slug'
      path: '/forum/$slug'
      fullPath: '/forum/$slug'
      preLoaderRoute: typeof ForumSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/$slug/': {
      id: '/forum/$slug/'
      path: '/'
      fullPath: '/forum/$slug/'
      preLoaderRoute: typeof ForumSlugIndexRouteImport
      parentRoute: typeof ForumSlugRoute
    }
    '/forum/$slug/$topicId': {
      id: '/forum/$slug/$topicId'
      path: '/$topicId'
      fullPath: '/forum/$slug/$topicId'
      preLoaderRoute: typeof ForumSlugTopicIdRouteImport
      parentRoute: typeof ForumSlugRoute
    }
  }
}

interface ForumSlugRouteChildren {
  ForumSlugTopicIdRoute: typeof ForumSlugTopicIdRoute
  ForumSlugIndexRoute: typeof ForumSlugIndexRoute
}

const ForumSlugRouteChildren: ForumSlugRouteChildren = {
  ForumSlugTopicIdRoute: ForumSlugTopicIdRoute,
  ForumSlugIndexRoute: ForumSlugIndexRoute,
}

const ForumSlugRouteWithChildren = ForumSlugRoute._addFileChildren(
  ForumSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminTymRoute: AdminTymRoute,
  KontaktRoute: KontaktRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServeryRoute: ServeryRoute,
  VipRoute: VipRoute,
  ForumSlugRoute: ForumSlugRouteWithChildren,
  NovinkyIdRoute: NovinkyIdRoute,
  ServerIdRoute: ServerIdRoute,
  ForumIndexRoute: ForumIndexRoute,
  NovinkyIndexRoute: NovinkyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
