/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VipRouteImport } from './routes/vip'
import { Route as ServeryRouteImport } from './routes/servery'
import { Route as NovinkyRouteImport } from './routes/novinky'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as ForumRouteImport } from './routes/forum'
import { Route as AdminTymRouteImport } from './routes/admin-tym'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServerIdRouteImport } from './routes/server.$id'
import { Route as NovinkyIdRouteImport } from './routes/novinky.$id'
import { Route as ForumSlugRouteImport } from './routes/forum.$slug'
import { Route as ForumSlugTopicIdRouteImport } from './routes/forum.$slug.$topicId'

const VipRoute = VipRouteImport.update({
  id: '/vip',
  path: '/vip',
  getParentRoute: () => rootRouteImport,
} as any)
const ServeryRoute = ServeryRouteImport.update({
  id: '/servery',
  path: '/servery',
  getParentRoute: () => rootRouteImport,
} as any)
const NovinkyRoute = NovinkyRouteImport.update({
  id: '/novinky',
  path: '/novinky',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumRoute = ForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTymRoute = AdminTymRouteImport.update({
  id: '/admin-tym',
  path: '/admin-tym',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerIdRoute = ServerIdRouteImport.update({
  id: '/server/$id',
  path: '/server/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NovinkyIdRoute = NovinkyIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => NovinkyRoute,
} as any)
const ForumSlugRoute = ForumSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ForumRoute,
} as any)
const ForumSlugTopicIdRoute = ForumSlugTopicIdRouteImport.update({
  id: '/$topicId',
  path: '/$topicId',
  getParentRoute: () => ForumSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-tym': typeof AdminTymRoute
  '/forum': typeof ForumRouteWithChildren
  '/kontakt': typeof KontaktRoute
  '/novinky': typeof NovinkyRouteWithChildren
  '/servery': typeof ServeryRoute
  '/vip': typeof VipRoute
  '/forum/$slug': typeof ForumSlugRouteWithChildren
  '/novinky/$id': typeof NovinkyIdRoute
  '/server/$id': typeof ServerIdRoute
  '/forum/$slug/$topicId': typeof ForumSlugTopicIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-tym': typeof AdminTymRoute
  '/forum': typeof ForumRouteWithChildren
  '/kontakt': typeof KontaktRoute
  '/novinky': typeof NovinkyRouteWithChildren
  '/servery': typeof ServeryRoute
  '/vip': typeof VipRoute
  '/forum/$slug': typeof ForumSlugRouteWithChildren
  '/novinky/$id': typeof NovinkyIdRoute
  '/server/$id': typeof ServerIdRoute
  '/forum/$slug/$topicId': typeof ForumSlugTopicIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-tym': typeof AdminTymRoute
  '/forum': typeof ForumRouteWithChildren
  '/kontakt': typeof KontaktRoute
  '/novinky': typeof NovinkyRouteWithChildren
  '/servery': typeof ServeryRoute
  '/vip': typeof VipRoute
  '/forum/$slug': typeof ForumSlugRouteWithChildren
  '/novinky/$id': typeof NovinkyIdRoute
  '/server/$id': typeof ServerIdRoute
  '/forum/$slug/$topicId': typeof ForumSlugTopicIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-tym'
    | '/forum'
    | '/kontakt'
    | '/novinky'
    | '/servery'
    | '/vip'
    | '/forum/$slug'
    | '/novinky/$id'
    | '/server/$id'
    | '/forum/$slug/$topicId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-tym'
    | '/forum'
    | '/kontakt'
    | '/novinky'
    | '/servery'
    | '/vip'
    | '/forum/$slug'
    | '/novinky/$id'
    | '/server/$id'
    | '/forum/$slug/$topicId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-tym'
    | '/forum'
    | '/kontakt'
    | '/novinky'
    | '/servery'
    | '/vip'
    | '/forum/$slug'
    | '/novinky/$id'
    | '/server/$id'
    | '/forum/$slug/$topicId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminTymRoute: typeof AdminTymRoute
  ForumRoute: typeof ForumRouteWithChildren
  KontaktRoute: typeof KontaktRoute
  NovinkyRoute: typeof NovinkyRouteWithChildren
  ServeryRoute: typeof ServeryRoute
  VipRoute: typeof VipRoute
  ServerIdRoute: typeof ServerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vip': {
      id: '/vip'
      path: '/vip'
      fullPath: '/vip'
      preLoaderRoute: typeof VipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servery': {
      id: '/servery'
      path: '/servery'
      fullPath: '/servery'
      preLoaderRoute: typeof ServeryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novinky': {
      id: '/novinky'
      path: '/novinky'
      fullPath: '/novinky'
      preLoaderRoute: typeof NovinkyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum': {
      id: '/forum'
      path: '/forum'
      fullPath: '/forum'
      preLoaderRoute: typeof ForumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-tym': {
      id: '/admin-tym'
      path: '/admin-tym'
      fullPath: '/admin-tym'
      preLoaderRoute: typeof AdminTymRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server/$id': {
      id: '/server/$id'
      path: '/server/$id'
      fullPath: '/server/$id'
      preLoaderRoute: typeof ServerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novinky/$id': {
      id: '/novinky/$id'
      path: '/$id'
      fullPath: '/novinky/$id'
      preLoaderRoute: typeof NovinkyIdRouteImport
      parentRoute: typeof NovinkyRoute
    }
    '/forum/$slug': {
      id: '/forum/$slug'
      path: '/$slug'
      fullPath: '/forum/$slug'
      preLoaderRoute: typeof ForumSlugRouteImport
      parentRoute: typeof ForumRoute
    }
    '/forum/$slug/$topicId': {
      id: '/forum/$slug/$topicId'
      path: '/$topicId'
      fullPath: '/forum/$slug/$topicId'
      preLoaderRoute: typeof ForumSlugTopicIdRouteImport
      parentRoute: typeof ForumSlugRoute
    }
  }
}

interface ForumSlugRouteChildren {
  ForumSlugTopicIdRoute: typeof ForumSlugTopicIdRoute
}

const ForumSlugRouteChildren: ForumSlugRouteChildren = {
  ForumSlugTopicIdRoute: ForumSlugTopicIdRoute,
}

const ForumSlugRouteWithChildren = ForumSlugRoute._addFileChildren(
  ForumSlugRouteChildren,
)

interface ForumRouteChildren {
  ForumSlugRoute: typeof ForumSlugRouteWithChildren
}

const ForumRouteChildren: ForumRouteChildren = {
  ForumSlugRoute: ForumSlugRouteWithChildren,
}

const ForumRouteWithChildren = ForumRoute._addFileChildren(ForumRouteChildren)

interface NovinkyRouteChildren {
  NovinkyIdRoute: typeof NovinkyIdRoute
}

const NovinkyRouteChildren: NovinkyRouteChildren = {
  NovinkyIdRoute: NovinkyIdRoute,
}

const NovinkyRouteWithChildren =
  NovinkyRoute._addFileChildren(NovinkyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminTymRoute: AdminTymRoute,
  ForumRoute: ForumRouteWithChildren,
  KontaktRoute: KontaktRoute,
  NovinkyRoute: NovinkyRouteWithChildren,
  ServeryRoute: ServeryRoute,
  VipRoute: VipRoute,
  ServerIdRoute: ServerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
